import React, { useState } from 'react';
import Matchup from './Matchup';
import { getTeamFromTeamManagers } from '../../utils/helperFunctions/universalFunctions';
import styles from './MatchupsAndBrackets.module.css';

export default function MatchupsAndBrackets({ matchupsData, leagueTeamManagers, bracketsData, playersInfo, leagueData }) {
    const [subView, setSubView] = useState('schedule');
    const [selectedWeek, setSelectedWeek] = useState(matchupsData.week);

    const handleWeekChange = (e) => setSelectedWeek(parseInt(e.target.value));
    const currentWeekData = matchupsData.matchupWeeks?.find(w => w.week === selectedWeek);
    const matchesArray = currentWeekData ? Object.values(currentWeekData.matchups) : [];

    const getPlayoffScore = (teamPoints) => {
        if (!teamPoints) return "0.00 -";
        let total = 0;
        let hasPoints = false;
        Object.values(teamPoints).forEach(arr => {
            if (Array.isArray(arr)) {
                hasPoints = true;
                total += arr.reduce((sum, p) => sum + (parseFloat(p) || 0), 0);
            }
        });
        return hasPoints ? `${total.toFixed(2)} -` : "0.00 -";
    };

    const BracketViewer = ({ bracketTree, isToiletBowl }) => {
        if (!bracketTree || !bracketTree.bracket || bracketTree.bracket.length === 0) {
            return <div className={styles.emptyState}>No playoff bracket data available for this league.</div>;
        }

        return (
            <div className={styles.bracketContainer}>
                <div className={styles.bracketWrapper}>
                    {bracketTree.bracket.map((roundMatches, roundIdx) => {
                        const isFinalsRound = roundIdx === bracketTree.bracket.length - 1;

                        // 1. Map Main Matches (Strip buggy native BYEs from Round 1)
                        const mainMatches = [];
                        roundMatches.forEach((match) => {
                            if (!match || match.length === 0) return;
                            const t1 = match[0] || {};
                            const t2 = match[1] || {};
                            
                            // Strip fake BYEs from R1 generated by buggy helper functions
                            const isFake = (t1.roster_id && !t2.roster_id && !t2.tFrom) || match.bye === true;
                            if (roundIdx === 0 && isFake) return;
                            
                            mainMatches.push({ match });
                        });

                        let displayMainMatches = [...mainMatches];

                        // 2. Inject Symmetrical BYE Blocks into Round 1
                        if (roundIdx === 0 && mainMatches.length === 2 && bracketTree.bracket.length > 1) {
                            const r1RosterIds = new Set();
                            mainMatches.forEach(m => {
                                if (m.match[0]?.roster_id) r1RosterIds.add(m.match[0].roster_id);
                                if (m.match[1]?.roster_id) r1RosterIds.add(m.match[1].roster_id);
                            });

                            // ONLY fetch the main matches from round 2, filtering out any sneaky consolation matches
                            const r2MainMatches = (bracketTree.bracket[1] || []).filter(m => {
                                const p = m.p || m[0]?.p || m[1]?.p || 1;
                                return p === 1; 
                            });

                            const byeTeams = [];
                            r2MainMatches.forEach(m => {
                                if (m[0]?.roster_id && !r1RosterIds.has(m[0].roster_id)) byeTeams.push(m[0]);
                                if (m[1]?.roster_id && !r1RosterIds.has(m[1].roster_id)) byeTeams.push(m[1]);
                            });

                            const uniqueByeTeams = Array.from(new Map(byeTeams.map(item => [item.roster_id, item])).values());

                            // Inject the two resting teams into the 1st and 3rd visual slots perfectly
                            if (uniqueByeTeams.length === 2) {
                                displayMainMatches = [
                                    { match: { team: uniqueByeTeams[0] }, isFakeBye: true },
                                    mainMatches[0],
                                    { match: { team: uniqueByeTeams[1] }, isFakeBye: true },
                                    mainMatches[1]
                                ];
                            }
                        }

                        // 3. Process Consolation Matches specifically for this round
                        const consolationMatches = [];
                        if (bracketTree.consolations) {
                            bracketTree.consolations.forEach(cons => {
                                if (cons[roundIdx] && cons[roundIdx].length > 0) {
                                    cons[roundIdx].forEach(cMatch => {
                                         let pVal = cMatch.p || cMatch[0]?.p || cMatch[1]?.p;
                                         consolationMatches.push({ match: cMatch, pVal });
                                    });
                                }
                            });
                        }

                        const renderMatchCard = (matchData, isMain, idx) => {
                            const { match, pVal, isFakeBye } = matchData;
                            
                            let t1 = {}, t2 = {};
                            if (isFakeBye) {
                                t1 = match.team || {};
                            } else {
                                t1 = match[0] || {};
                                t2 = match[1] || {};
                            }
                            
                            const meta1 = t1.roster_id ? getTeamFromTeamManagers(leagueTeamManagers, t1.roster_id, matchupsData.year) : null;
                            const meta2 = t2.roster_id ? getTeamFromTeamManagers(leagueTeamManagers, t2.roster_id, matchupsData.year) : null;

                            // Explicit Badges & Labels
                            let label = null;
                            if (isMain && isFinalsRound) {
                                label = isToiletBowl ? '💩 King (Last Place)' : '🏆 Championship';
                            } else if (!isMain) {
                                if (isToiletBowl) {
                                    label = isFinalsRound ? '8th Place' : 'Consolation';
                                } else {
                                    if (pVal === 3 || isFinalsRound) label = '3rd Place';
                                    else if (pVal === 5 || roundIdx === bracketTree.bracket.length - 2) label = '5th Place';
                                    else if (pVal === 7 || roundIdx === bracketTree.bracket.length - 3) label = '7th Place';
                                    else label = 'Consolation';
                                }
                            }

                            return (
                                <div key={t1.roster_id || Math.random()} className={styles.matchCard}>
                                    {label && <div className={styles.matchLabel}>{label}</div>}

                                    {/* Team 1 Row */}
                                    <div className={styles.teamRow}>
                                        {meta1 ? (
                                            <div className={styles.teamInfo}>
                                                <img src={meta1.avatar} className={styles.avatar} alt="t1" />
                                                <span className={styles.teamName}>{meta1.name}</span>
                                            </div>
                                        ) : (
                                            <div className={styles.teamInfo}>
                                                <div className={styles.avatarPlaceholder} />
                                                <span className={styles.teamName}>{t1.tFrom ? "TBD" : "BYE"}</span>
                                            </div>
                                        )}
                                        <span className={styles.score}>{t1.roster_id ? getPlayoffScore(t1.points) : ""}</span>
                                    </div>

                                    {/* Bottom Half: Render centered BYE block or standard TBD Team 2 row */}
                                    {isFakeBye ? (
                                        <div className={styles.byeBlockText}>BYE</div>
                                    ) : (
                                        <div className={styles.teamRow}>
                                            {meta2 ? (
                                                <div className={styles.teamInfo}>
                                                    <img src={meta2.avatar} className={styles.avatar} alt="t2" />
                                                    <span className={styles.teamName}>{meta2.name}</span>
                                                </div>
                                            ) : (
                                                <div className={styles.teamInfo}>
                                                    <div className={styles.avatarPlaceholder} />
                                                    <span className={styles.teamName}>{t2.tFrom ? "TBD" : "BYE"}</span>
                                                </div>
                                            )}
                                            <span className={styles.score}>{t2.roster_id ? getPlayoffScore(t2.points) : ""}</span>
                                        </div>
                                    )}
                                </div>
                            );
                        };

                        return (
                            <div key={roundIdx} className={styles.bracketColumn}>
                                <div className={styles.roundHeader}>
                                    (Week {(bracketsData?.playoffsStart || 15) + roundIdx})
                                </div>
                                
                                <div className={styles.roundColumnLayout}>
                                    {/* Main Upper Tree Path fixed layout */}
                                    <div className={styles.mainMatchesSection}>
                                        {displayMainMatches.map((m, idx) => renderMatchCard(m, true, idx))}
                                    </div>

                                    {/* Lower Consolation Tree Anchor dropped to the bottom */}
                                    {consolationMatches.length > 0 && (
                                        <div className={styles.consolationMatchesSection}>
                                            {consolationMatches.map((m, idx) => renderMatchCard(m, false, idx))}
                                        </div>
                                    )}
                                </div>
                            </div>
                        );
                    })}
                </div>
            </div>
        );
    };

    return (
        <div className={styles.container}>
            <div className={styles.subNavigation}>
                <button className={`${styles.subToggleBtn} ${subView === 'schedule' ? styles.activeSub : ''}`} onClick={() => setSubView('schedule')}>Weekly Schedule</button>
                <button className={`${styles.subToggleBtn} ${subView === 'winners' ? styles.activeSub : ''}`} onClick={() => setSubView('winners')}>Championship Bracket</button>
                <button className={`${styles.subToggleBtn} ${subView === 'losers' ? styles.activeSub : ''}`} onClick={() => setSubView('losers')}>Toilet Bowl</button>
            </div>

            {subView === 'schedule' && (
                <>
                    <div className={styles.headerControls}>
                        <h2 className={styles.title}>League Schedule</h2>
                        <select className={styles.weekSelect} value={selectedWeek} onChange={handleWeekChange}>
                            {matchupsData.matchupWeeks.map(w => <option key={w.week} value={w.week}>Week {w.week}</option>)}
                        </select>
                    </div>
                    <div className={styles.scheduleGrid}>
                        {matchesArray.map((m, i) => <Matchup key={i} matchup={m} players={playersInfo.players} leagueTeamManagers={leagueTeamManagers} year={matchupsData.year} week={selectedWeek} leagueData={leagueData} initialExpanded={false} />)}
                    </div>
                </>
            )}
            
            {subView === 'winners' && <BracketViewer bracketTree={bracketsData?.champs} isToiletBowl={false} />}
            {subView === 'losers' && <BracketViewer bracketTree={bracketsData?.losers} isToiletBowl={true} />}
        </div>
    );
}